"""
Comprehensive Basketball Player Names List
For sports card categorization - includes nicknames and alternate spellings
"""

BASKETBALL_PLAYERS = [
    # ============================================================
    # CURRENT NBA STARS (2020s Era)
    # ============================================================
    "anthony edwards", "ant edwards", "ant man edwards", "a1 from day 1",
    "tyrese haliburton", "haliburton",
    "tyrese maxey", "maxey",
    "paolo banchero", "banchero",
    "victor wembanyama", "wembanyama", "wemby", "the alien",
    "chet holmgren", "holmgren", "chet",
    "scottie barnes", "barnes",
    "evan mobley", "mobley",
    "franz wagner", "wagner",
    "donovan mitchell", "spida", "spida mitchell",
    "trae young", "ice trae", "trae",
    "dejounte murray", "murray",
    "shai gilgeous-alexander", "sga", "shai", "gilgeous-alexander",
    "devin booker", "d-book", "booker", "book",
    "damian lillard", "dame", "dame time", "dame lillard", "lillard",
    "karl-anthony towns", "kat", "towns", "karl anthony towns",
    "derrick rose", "d-rose", "d rose", "rose",
    "jimmy butler", "jimmy buckets", "butler",
    "bam adebayo", "adebayo", "bam",
    "jaylen brown", "j brown", "brown",
    "domantas sabonis", "sabonis",
    "de'aaron fox", "fox", "deaaron fox", "swipa",
    "fred vanvleet", "vanvleet", "fvv",
    "jrue holiday", "holiday",
    "khris middleton", "middleton",
    "pascal siakam", "siakam", "spicy p",
    "og anunoby", "anunoby",
    "mikal bridges", "bridges",
    "anfernee simons", "ant simons", "simons",
    "jarrett allen", "allen",
    "darius garland", "garland",
    "alperen sengun", "sengun",
    "jalen brunson", "brunson",
    "julius randle", "randle",
    "brandon ingram", "ingram", "bi", "b ingram",
    "cj mccollum", "c.j. mccollum", "mccollum",
    "desmond bane", "bane",
    "jaren jackson jr", "jjj", "jaren jackson", "triple j",
    "jamal murray", "j murray",
    "michael porter jr", "mpj", "michael porter", "porter jr",
    "aaron gordon", "gordon", "ag",
    "lauri markkanen", "markkanen", "lauri",
    "tyler herro", "herro", "boy wonder",
    "immanuel quickley", "quickley", "iq",
    "jalen williams", "j williams", "jwill",
    "josh hart", "hart",
    "austin reaves", "reaves", "ar-15", "hillbilly kobe",
    "max strus", "strus",
    "coby white", "white",

    # ============================================================
    # RECENT DRAFT CLASSES (2020-2025)
    # ============================================================
    "jalen green", "j green", "green",
    "cade cunningham", "cade", "cunningham",
    "josh giddey", "giddey",
    "keegan murray", "k murray",
    "bennedict mathurin", "mathurin", "benn mathurin",
    "jaden ivey", "ivey",
    "jabari smith jr", "jabari smith", "jabari",
    "scoot henderson", "henderson", "scoot",
    "amen thompson", "thompson",
    "ausar thompson",
    "brandon miller", "b miller", "miller",
    "jarace walker", "walker",
    "gradey dick", "dick",
    "taylor hendricks", "hendricks",
    "keyonte george", "george",
    "cam whitmore", "whitmore",
    "bilal coulibaly", "coulibaly",
    "dereck lively ii", "lively", "dereck lively",
    "cooper flagg", "flagg",
    "dylan harper", "harper",
    "ace bailey", "bailey",
    "vj edgecombe", "edgecombe",
    "kon knueppel", "knueppel",
    "tre johnson", "t johnson",
    "kasparas jakucionis", "jakucionis",
    "airious bailey", "a bailey",
    "nolan traore", "traore",
    "egor demin", "demin",
    "khaman maluach", "maluach",
    "reed sheppard", "sheppard",
    "stephon castle", "castle",
    "dalton knecht", "knecht",
    "donovan clingan", "clingan",
    "rob dillingham", "dillingham",
    "matas buzelis", "buzelis",
    "zach edey", "edey",
    "tidjane salaun", "salaun",
    "devin carter", "d carter",
    "johnny furphy", "furphy",
    "cody williams", "c williams",
    "jared mccain", "mccain",
    "ron holland", "holland",
    "ja'kobe walter", "jakobe walter", "walter",
    "zaccharie risacher", "risacher",
    "alex sarr", "sarr",

    # ============================================================
    # WNBA STARS
    # ============================================================
    "caitlin clark", "clark", "caitlin",
    "angel reese", "reese", "angel", "bayou barbie",
    "cameron brink", "cam brink", "brink",
    "a'ja wilson", "aja wilson", "a'ja", "wilson",
    "breanna stewart", "stewie", "stewart",
    "sabrina ionescu", "ionescu", "sabrina",
    "kelsey plum", "plum",
    "chelsea gray", "gray",
    "jackie young", "j young",
    "alyssa thomas", "a thomas",
    "jonquel jones", "jj", "jones",
    "candace parker", "parker", "candace",
    "diana taurasi", "taurasi", "diana", "dee", "the goat",
    "sue bird", "bird",
    "brittney griner", "griner", "bg",
    "elena delle donne", "delle donne", "edd",
    "nneka ogwumike", "ogwumike",
    "courtney williams", "court williams",
    "dearica hamby", "hamby",
    "napheesa collier", "collier",
    "kayla mcbride", "mcbride",
    "skylar diggins-smith", "diggins", "skylar",
    "maya moore", "moore",
    "lisa leslie", "leslie",
    "sheryl swoopes", "swoopes",
    "tina thompson", "t thompson",
    "tamika catchings", "catchings",
    "lauren jackson", "l jackson",
    "becky hammon", "hammon",
    "aliyah boston", "boston", "aliyah",
    "rhyne howard", "howard",
    "deja kelly", "d kelly",
    "arike ogunbowale", "arike",
    "jewell loyd", "loyd",
    "paige bueckers", "bueckers", "paige",
    "juju watkins", "watkins", "juju",
    "hailey van lith", "van lith",
    "flau'jae johnson", "flaujae", "flau'jae",

    # ============================================================
    # CURRENT/RECENT LEGENDS (Still Active or Recently Retired)
    # ============================================================
    "lebron james", "lebron", "king james", "lbj", "the king", "bron",
    "stephen curry", "steph curry", "curry", "steph", "chef curry", "baby faced assassin",
    "kevin durant", "kd", "durant", "the slim reaper", "easy money sniper",
    "giannis antetokounmpo", "giannis", "greek freak", "the greek freak",
    "luka doncic", "luka", "doncic", "luka magic", "the don",
    "ja morant", "ja", "morant", "twelve",
    "jayson tatum", "tatum", "jt", "the problem",
    "joel embiid", "embiid", "the process", "troel",
    "nikola jokic", "jokic", "the joker", "joker", "big honey",
    "kawhi leonard", "kawhi", "leonard", "the klaw", "the claw", "fun guy",
    "paul george", "pg", "pg13", "playoff p",
    "chris paul", "cp3", "the point god",
    "kyrie irving", "kyrie", "uncle drew", "kai",
    "james harden", "harden", "the beard",
    "russell westbrook", "westbrook", "russ", "brodie", "mr triple double",
    "anthony davis", "ad", "the brow", "street clothes",
    "zion williamson", "zion", "williamson",
    "lamelo ball", "lamelo", "melo ball", "melo",
    "lonzo ball", "lonzo", "zo",
    "draymond green", "draymond", "day day",
    "klay thompson", "klay", "thompson", "splash brother",
    "andrew wiggins", "wiggins", "wiggs",
    "jordan poole", "poole",
    "deandre ayton", "ayton",

    # ============================================================
    # CLASSIC LEGENDS (Retired)
    # ============================================================
    "michael jordan", "jordan", "mj", "his airness", "air jordan", "the goat",
    "kobe bryant", "kobe", "black mamba", "mamba", "kb24", "bean",
    "shaquille o'neal", "shaq", "shaquille", "o'neal", "the big diesel",
    "the big aristotle", "shaq diesel", "superman",
    "magic johnson", "magic", "earvin johnson", "earvin",
    "larry bird", "bird", "larry legend", "the hick from french lick",
    "kareem abdul-jabbar", "kareem", "abdul-jabbar", "cap", "the captain",
    "wilt chamberlain", "wilt", "chamberlain", "wilt the stilt", "the big dipper",
    "bill russell", "russell", "mr eleven rings",
    "oscar robertson", "oscar", "the big o", "big o",
    "jerry west", "west", "the logo", "mr clutch",
    "elgin baylor", "baylor", "elgin",
    "bob cousy", "cousy", "the houdini of the hardwood",
    "john havlicek", "havlicek", "hondo",
    "julius erving", "dr j", "dr. j", "doctor j", "erving", "julius",
    "moses malone", "moses", "malone", "chairman of the boards",
    "george mikan", "mikan", "mr basketball",
    "bob pettit", "pettit",
    "dave cowens", "cowens",
    "willis reed", "reed",
    "earl monroe", "earl the pearl", "monroe",
    "dave bing", "bing",
    "nate archibald", "tiny archibald", "nate tiny archibald", "archibald",
    "pete maravich", "pistol pete", "maravich", "pistol",
    "walt frazier", "clyde", "frazier",
    "bernard king", "king",
    "dominique wilkins", "dominique", "wilkins", "the human highlight film",
    "human highlight reel", "nique",
    "clyde drexler", "drexler", "the glide", "clyde the glide",
    "gary payton", "payton", "the glove", "gp",
    "john stockton", "stockton", "stock",
    "karl malone", "malone", "the mailman", "mailman",
    "allen iverson", "iverson", "ai", "the answer", "a.i.",
    "dirk nowitzki", "dirk", "nowitzki", "the german wunderkind",
    "the tall baller from the g",
    "tim duncan", "duncan", "the big fundamental", "timmy",
    "dwyane wade", "wade", "d-wade", "flash", "d wade",
    "scottie pippen", "pippen", "pip", "no tippin pippen",
    "charles barkley", "barkley", "sir charles", "the round mound of rebound", "chuck",
    "hakeem olajuwon", "hakeem", "olajuwon", "the dream", "dream",
    "david robinson", "robinson", "the admiral", "admiral",
    "patrick ewing", "ewing", "pat ewing",
    "isiah thomas", "isiah", "zeke",
    "reggie miller", "reggie", "miller",
    "ray allen", "ray", "jesus shuttlesworth", "ray ray",
    "paul pierce", "pierce", "the truth", "truth",
    "kevin garnett", "kg", "garnett", "the big ticket", "big ticket",
    "vince carter", "vinsanity", "carter", "vc", "half man half amazing", "air canada",
    "tracy mcgrady", "tmac", "t-mac", "mcgrady",
    "grant hill", "hill",
    "penny hardaway", "penny", "hardaway", "anfernee hardaway",
    "alonzo mourning", "mourning", "zo",
    "chris webber", "webber", "c-webb", "cwebb",
    "jason kidd", "kidd", "j kidd",
    "steve nash", "nash",
    "amare stoudemire", "amare", "stoudemire", "stat",
    "yao ming", "yao", "ming",
    "manu ginobili", "manu", "ginobili",
    "tony parker", "tp", "parker",
    "pau gasol", "pau", "gasol",
    "marc gasol", "marc",
    "carmelo anthony", "melo", "carmelo", "me7o",
    "dwight howard", "dwight", "howard", "d12", "superman",
    "chris bosh", "bosh", "cb4",
    "blake griffin", "blake", "griffin",
    "derrick rose", "drose", "d rose", "mvp rose",
    "rajon rondo", "rondo", "playoff rondo",
    "john wall", "wall", "j wall",
    "demarcus cousins", "cousins", "boogie",
    "demar derozan", "derozan", "deebo",
    "gordon hayward", "hayward",
    "kemba walker", "kemba", "cardiac kemba",
    "ben simmons", "simmons",
    "markelle fultz", "fultz",
    "rj barrett", "barrett", "rj",
    "collin sexton", "sexton", "young bull",

    # ============================================================
    # HISTORICAL/VINTAGE GREATS
    # ============================================================
    "george gervin", "gervin", "iceman", "the iceman",
    "adrian dantley", "dantley",
    "alex english", "english",
    "robert parish", "parish", "the chief",
    "james worthy", "worthy", "big game james",
    "dennis rodman", "rodman", "the worm", "worm",
    "bill laimbeer", "laimbeer",
    "joe dumars", "dumars",
    "rick barry", "barry",
    "elvin hayes", "hayes", "the big e",
    "wes unseld", "unseld",
    "bill walton", "walton",
    "jack sikma", "sikma",
    "dan issel", "issel",
    "artis gilmore", "gilmore", "the a-train",
    "spencer haywood", "haywood",
    "connie hawkins", "hawkins", "the hawk",
    "sam jones", "s jones",
    "k.c. jones", "kc jones",
    "tom heinsohn", "heinsohn",
    "dolph schayes", "schayes",
    "paul arizin", "arizin",
    "hal greer", "greer",
    "billy cunningham", "cunningham", "kangaroo kid",
    "dave debusschere", "debusschere",
    "jerry lucas", "lucas",
    "nate thurmond", "thurmond",
    "lenny wilkens", "wilkens",
    "kevin mchale", "mchale",
    "dennis johnson", "dj", "d johnson",
    "sidney moncrief", "moncrief", "sid",
    "marques johnson", "m johnson",
    "bob lanier", "lanier",
    "lou hudson", "hudson", "sweet lou",
    "chet walker", "c walker",
    "gail goodrich", "goodrich",
    "jerry sloan", "sloan",
    "dick van arsdale", "van arsdale",
    "tom van arsdale",
    "calvin murphy", "murphy",
    "world b free", "lloyd free",
    "maurice cheeks", "mo cheeks", "cheeks",
    "fat lever", "lever",
    "mark aguirre", "aguirre",
    "terry cummings", "cummings",
    "jack twyman", "twyman",
    "maurice lucas", "lucas",
    "darryl dawkins", "dawkins", "chocolate thunder",
    "george mcginnis", "mcginnis",

    # ============================================================
    # MODERN ROLE PLAYERS & NOTABLE NAMES
    # ============================================================
    "andre iguodala", "iguodala", "iggy",
    "al horford", "horford",
    "marcus smart", "smart",
    "robert williams", "timelord", "rob williams",
    "grant williams", "g williams",
    "brook lopez", "lopez",
    "bobby portis", "portis", "bobby buckets",
    "malik monk", "monk",
    "kelly oubre", "oubre", "tsunami papi",
    "norman powell", "powell",
    "gary trent jr", "gary trent", "gtj",
    "precious achiuwa", "achiuwa",
    "nikola vucevic", "vucevic", "vooch",
    "jonas valanciunas", "valanciunas", "jv",
    "clint capela", "capela",
    "john collins", "collins",
    "rudy gobert", "gobert", "the stifle tower", "gobzilla",
    "mike conley", "conley",
    "malik beasley", "beasley",
    "terry rozier", "rozier", "scary terry",
    "miles bridges", "m bridges",
    "myles turner", "turner",
    "buddy hield", "hield", "buddy buckets",
    "monte morris", "m morris",
    "bruce brown", "b brown",
    "derrick white", "d white",
    "marcus morris", "mook",
    "markieff morris", "kief",
    "kyle kuzma", "kuzma", "kuz",
    "cameron johnson", "cam johnson",
    "spencer dinwiddie", "dinwiddie",
    "shake milton", "milton",
]

# Count of unique entries
if __name__ == "__main__":
    print(f"Total basketball player entries: {len(BASKETBALL_PLAYERS)}")
